/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      { source: "/comingSoon", destination: "/pages/comingSoon" },
      { source: "/services", destination: "/pages/services" },
      { source: "/contact", destination: "/pages/contactUs" },
      { source: "/about", destination: "/pages/aboutUs" },
      { source: "/who-we-are", destination: "/pages/whoWeAre" },
      { source: "/partners", destination: "/pages/partners" },
      { source: "/timeline", destination: "/pages/timeline" },
      { source: "/leader", destination: "/pages/leadershipTeam" },
      { source: "/partner-with-us", destination: "/pages/partnerWithUs" },
      { source: "/career", destination: "/pages/careers" },
      { source: "/award", destination: "/pages/award" },
      { source: "/news", destination: "/pages/news&press" },
      { source: "/privacy", destination: "/pages/privacy" },
      { source: "/events", destination: "/pages/events" },
      { source: "/events/:pageUrl", destination: "/pages/events/:pageUrl" },
      { source: "/blogs", destination: "/pages/blogs" },
      { source: "/blogs/:id", destination: "/pages/blogs/:id" },
      { source: "/personalizedUniversity", destination: "/pages/ServicesPages/personalizedUniversity" },
      { source: "/applicationAssistance", destination: "/pages/ServicesPages/applicationAssistance" },
      { source: "/aidGuidance", destination: "/pages/ServicesPages/aidGuidance" },
      { source: "/immigrationSupport", destination: "/pages/ServicesPages/immigrationSupport" },
      { source: "/travelAssistance", destination: "/pages/ServicesPages/travelAssistance" },
      { source: "/postGraduationAid", destination: "/pages/ServicesPages/postGraduationAid" },
      { source: "/admissionProcess", destination: "/pages/ServicesPages/admissionProcess" },
      { source: "/studentGuidance", destination: "/pages/ServicesPages/studentGuidance" },
      { source: "/globalNetwork", destination: "/pages/ServicesPages/globalNetwork" },
      { source: "/studentSuccess", destination: "/pages/ServicesPages/studentSuccess" },
      { source: "/recruitmentSupport", destination: "/pages/ServicesPages/recruitmentSupport" },
      { source: "/collaboration", destination: "/pages/ServicesPages/collaboration" },
      { source: "/logIn", destination: "/pages/logIn" },
      { source: "/registration", destination: "/pages/registration" },
      { source: "/blog-editor", destination: "/pages/blog-editor" },
      { source: "/study-destinations", destination: "/pages/study-destinations" }, 
      { source: "/study-destinations/:url", destination: "/pages/study-destinations/:url" },
      { source: "/study-destinations/:url/:Name", destination: "/pages/study-destinations/:url/:Name" },
      { source: "/admin", destination: "/pages/admin" },
      { source: "/admin/blogs", destination: "/pages/admin/blogs" },
      { source: "/admin/events", destination: "/pages/admin/events" },
      { source: "/admin/welcomeModal", destination: "/pages/admin/welcomeModal" },
      { source: "/admin/blogs/edit", destination: "/pages/admin/blogs/edit" },
      { source: "/admin/events/add", destination: "/pages/admin/events/add" },
      { source: "/admin/events/edit/:id", destination: "/pages/admin/events/edit/:id" },
      {source:"/ModalEventRegistration", destination:"/pages/ModalEventRegistration"},
      // { source: "/study-destinations/study-in-the-uk/:Name", destination: "/pages/study-destinations/study-in-the-uk/:Name", },
      // { source: "/study-destinations/study-in-the-usa", destination: "/pages/study-destinations/study-in-the-usa" },
      // { source: "/study-destinations/study-in-the-australia", destination: "/pages/study-destinations/study-in-the-australia", },
      // { source: "/study-destinations/study-in-the-canada", destination: "/pages/study-destinations/study-in-the-canada" },
      // { source: "/study-destinations/study-in-the-germany", destination: "/pages/study-destinations/study-in-the-germany" },
      // { source: "/study-destinations/study-in-the-new-zealand", destination: "/pages/study-destinations/study-in-the-new-zealand", },
      // { source: "/study-destinations/study-in-the-uae", destination: "/pages/study-destinations/study-in-the-uae" },
      // { source: "/study-destinations/study-in-the-georgia", destination: "/pages/study-destinations/study-in-the-georgia" },
      // { source: "/study-destinations/study-in-the-finland", destination: "/pages/study-destinations/study-in-the-finland" },
      // { source: "/study-destinations/study-in-the-cyprus", destination: "/pages/study-destinations/study-in-the-cyprus" },
      // { source: "/study-destinations/study-in-the-switzerland", destination: "/pages/study-destinations/study-in-the-switzerland", },
      // { source: "/study-destinations/study-in-the-france", destination: "/pages/study-destinations/study-in-the-france" },
      // { source: "/study-destinations/study-in-the-west-indies", destination: "/pages/study-destinations/study-in-the-west-indies", },
      { source: "/singleUniversity/:Name", destination: "/pages/singleUniversity/:Name", }
    ];
  },
  images: {
    domains: ["i.ibb.co", "i.ibb.co.com"],
    unoptimized: true,
  },
};

export default nextConfig;
